# Generated by Django 3.0.6 on 2020-05-15 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serviceprovider',
            old_name='local_government_are',
            new_name='local_government_area',
        ),
        migrations.RenameField(
            model_name='serviceprovider',
            old_name='year_of_experience',
            new_name='years_of_experience',
        ),
    ]
