# Generated by Django 3.0.6 on 2020-05-15 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20200515_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceprovider',
            name='supporting_document',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
